version: "3"

services:
  app:
    build:
      context: "confluence"
      args:
        CONFLUENCE_VERSION: ${CONFLUENCE_VERSION}
        IMAGE_PREFIX: ${IMAGE_PREFIX:-''}
    image: xsharp/confluence:${CONFLUENCE_VERSION}
    container_name: confluence-app
    hostname: "confluenceapp"
    working_dir: "/opt/atlassian/confluence"
    depends_on:
      - db
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - confluencedata:/var/atlassian/application-data/confluence
    restart: always
    env_file:
      - ./.env
    environment:
      - TZ='America/Los_Angeles'
      - JVM_MINIMUM_MEMORY=${JVM_MINIMUM_MEMORY}
      - JVM_MAXIMUM_MEMORY=${JVM_MAXIMUM_MEMORY}
      - JVM_RESERVED_CODE_CACHE_SIZE=${JVM_RESERVED_CODE_CACHE_SIZE}
      
      - ATL_PROXY_NAME=${ATL_PROXY_NAME}
      - ATL_PROXY_PORT=${ATL_PROXY_PORT}
      - ATL_TOMCAT_SCHEME=${ATL_TOMCAT_SCHEME}
      - ATL_TOMCAT_SECURE=${ATL_TOMCAT_SECURE}
        
      # - HTTP_PROXY=${HTTP_PROXY}
      # - HTTPS_PROXY=${HTTPS_PROXY}
      # - NO_PROXY=${NO_PROXY}
    networks:
      - confluence

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: confluence-postgres
    hostname: "confluencedb"
    environment:
      - TZ='America/Los_Angeles'
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--locale=en_US.UTF-8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - confluence

networks:
  confluence:
    driver: bridge

volumes:
  pgdata:
  confluencedata:
